

# This file was *autogenerated* from the file b.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3)
x=var('x')
eq=x**_sage_const_4  * (x-_sage_const_2 )*(x+_sage_const_3 )
solutions=find_local_maximum(eq)
print(solutions)

